import type { Metadata } from 'next'
import { Teko } from 'next/font/google'
import './globals.css'
import Head from 'next/head'

const teko = Teko({
  preload: true,
  subsets: [
    'latin'
  ],
  style: [
    'normal'
  ],
  weight: [
    '300',
    '500'
  ]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <title>@JuanCSUCoder CV</title>
      </Head>
      <body className={teko.className}>{children}</body>
    </html>
  )
}
